# Generated by Django 5.2.17 on 2026-08-12 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysalesreport',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='stores.store'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignanalytics',
            unique_together={('organization', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='customeranalytics',
            unique_together={('organization', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='dailysalesreport',
            unique_together={('organization', 'store', 'date')},
        ),
    ]
