# Generated by Django 5.1 on 2026-10-05 13:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
        ('customers', '0004_customer_portal_token'),
        ('organizations', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBundle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('original_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bundle_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('affinity_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_published', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
                ('products', models.ManyToManyField(related_name='bundles', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessAlert',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(db_index=True, max_length=100)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='WARNING', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('entity_type', models.CharField(blank=True, max_length=50)),
                ('entity_id', models.CharField(blank=True, max_length=100)),
                ('recommended_action', models.CharField(blank=True, max_length=255)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'severity', 'is_dismissed'], name='analytics_b_organiz_de05a9_idx'), models.Index(fields=['organization', 'created_at'], name='analytics_b_organiz_aecea8_idx')],
            },
        ),
        migrations.CreateModel(
            name='BusinessHealthSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('overall_score', models.PositiveSmallIntegerField(default=75)),
                ('sales_growth_score', models.PositiveSmallIntegerField(default=75)),
                ('retention_score', models.PositiveSmallIntegerField(default=75)),
                ('loyalty_score', models.PositiveSmallIntegerField(default=75)),
                ('marketing_score', models.PositiveSmallIntegerField(default=75)),
                ('product_performance_score', models.PositiveSmallIntegerField(default=75)),
                ('weakest_area', models.CharField(default='Customer Retention', max_length=100)),
                ('metrics_data', models.JSONField(blank=True, default=dict)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['organization', 'date'], name='analytics_b_organiz_813f7f_idx')],
                'unique_together': {('organization', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ChurnPrediction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('churn_probability', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('churn_risk', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='LOW', max_length=20)),
                ('prediction_reason', models.TextField(blank=True)),
                ('risk_factors', models.JSONField(blank=True, default=list)),
                ('recommended_action', models.CharField(blank=True, max_length=100)),
                ('predicted_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='churn_prediction', to='customers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
            ],
            options={
                'ordering': ['-churn_probability'],
                'indexes': [models.Index(fields=['organization', 'churn_risk'], name='analytics_c_organiz_56162c_idx'), models.Index(fields=['organization', 'churn_probability'], name='analytics_c_organiz_c0b71d_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerHealthProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('health_score', models.PositiveSmallIntegerField(default=50)),
                ('health_status', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('HEALTHY', 'Healthy'), ('STABLE', 'Stable'), ('AT_RISK', 'At Risk'), ('CRITICAL', 'Critical')], db_index=True, default='STABLE', max_length=20)),
                ('risk_factors', models.JSONField(blank=True, default=list)),
                ('positive_factors', models.JSONField(blank=True, default=list)),
                ('recommended_action', models.CharField(blank=True, max_length=100)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to='customers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
            ],
            options={
                'ordering': ['-health_score'],
                'indexes': [models.Index(fields=['organization', 'health_status'], name='analytics_c_organiz_2722bb_idx'), models.Index(fields=['organization', 'health_score'], name='analytics_c_organiz_84c789_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerRFMProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recency_days', models.PositiveIntegerField(default=0)),
                ('frequency_count', models.PositiveIntegerField(default=0)),
                ('monetary_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('r_score', models.PositiveSmallIntegerField(default=1)),
                ('f_score', models.PositiveSmallIntegerField(default=1)),
                ('m_score', models.PositiveSmallIntegerField(default=1)),
                ('rfm_score', models.CharField(db_index=True, default='111', max_length=10)),
                ('segment', models.CharField(db_index=True, default='New Customers', max_length=50)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rfm_profile', to='customers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
            ],
            options={
                'ordering': ['-calculated_at'],
                'indexes': [models.Index(fields=['organization', 'segment'], name='analytics_c_organiz_884f3b_idx'), models.Index(fields=['organization', 'rfm_score'], name='analytics_c_organiz_9d1cc1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductAffinity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('co_occurrence_count', models.PositiveIntegerField(default=0)),
                ('affinity_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('confidence', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('lift', models.DecimalField(decimal_places=2, default=1.0, max_digits=8)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
                ('product_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affinities_from', to='products.product')),
                ('product_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affinities_to', to='products.product')),
            ],
            options={
                'ordering': ['-affinity_score'],
                'indexes': [models.Index(fields=['organization', 'product_a'], name='analytics_p_organiz_4e4019_idx'), models.Index(fields=['organization', 'affinity_score'], name='analytics_p_organiz_d7603c_idx')],
                'unique_together': {('organization', 'product_a', 'product_b')},
            },
        ),
    ]
