# Generated by Django 5.1 on 2026-10-05 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='review',
            new_name='engagement__organiz_aa1c01_idx',
            old_name='eng_review_org_rating',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='engagement__custome_78937e_idx',
            old_name='eng_review_cust_created',
        ),
        migrations.AlterField(
            model_name='referral',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='review',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization'),
        ),
    ]
