# Generated by Django 5.1 on 2026-09-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_customer_id'),
        ('organizations', '0001_initial'),
        ('stores', '0002_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('external_transaction_id', ''), _negated=True), fields=('organization', 'external_transaction_id'), name='unique_org_non_empty_external_tx'),
        ),
    ]
