# Generated by Django 5.2.17 on 2026-08-12 10:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('trigger', models.CharField(choices=[('purchase_completed', 'Purchase Completed'), ('new_customer', 'New Customer'), ('customer_birthday', 'Customer Birthday'), ('customer_anniversary', 'Customer Anniversary'), ('inactive_customer', 'Inactive Customer'), ('coupon_expiry_reminder', 'Coupon Expiry Reminder'), ('loyalty_expiry_reminder', 'Loyalty Expiry Reminder'), ('review_request', 'Review Request')], max_length=50)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('delay_hours', models.PositiveIntegerField(default=0)),
                ('action', models.CharField(choices=[('send_whatsapp', 'Send WhatsApp Message'), ('send_email', 'Send Email'), ('create_coupon', 'Create Coupon'), ('award_loyalty', 'Award Loyalty Points'), ('update_segment', 'Update Customer Segment')], max_length=50)),
                ('action_config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('execution_count', models.PositiveIntegerField(default=0)),
                ('last_executed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AutomationExecution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('trigger_data', models.JSONField(blank=True, default=dict)),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='automations.automation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
