# Generated by Django 5.2.17 on 2026-08-12 10:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInsight',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insight_type', models.CharField(choices=[('churn_risk', 'Churn Risk'), ('lifetime_value', 'Lifetime Value'), ('purchase_prediction', 'Purchase Prediction'), ('product_affinity', 'Product Affinity'), ('segment_suggestion', 'Segment Suggestion')], max_length=50)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('recommendation', models.TextField(blank=True)),
                ('model_version', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIContentGeneration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('campaign_message', 'Campaign Message'), ('coupon_description', 'Coupon Description'), ('review_reply', 'Review Reply'), ('whatsapp_template', 'WhatsApp Template')], max_length=30)),
                ('prompt', models.TextField()),
                ('generated_content', models.TextField(blank=True)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AISegmentation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('rules', models.JSONField(default=dict)),
                ('customer_count', models.PositiveIntegerField(default=0)),
                ('is_auto_generated', models.BooleanField(default=False)),
                ('last_calculated_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
