# Generated by Django 5.1 on 2026-10-05 14:33

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
        ('customers', '0004_customer_portal_token'),
        ('organizations', '0001_initial'),
        ('stores', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_type', models.CharField(choices=[('RETAIL', 'Retail Store'), ('HARDWARE', 'Hardware & Sanitary'), ('JEWELLERY', 'Jewellery & Gems'), ('AUTO_SPARES', 'Auto Spare Parts'), ('ELECTRONICS', 'Consumer Electronics'), ('GROCERY', 'Grocery & Supermarket'), ('CLOTHING', 'Clothing & Apparel'), ('FURNITURE', 'Furniture & Home'), ('ELECTRICAL', 'Electrical Equipment'), ('MOBILE_COMPUTER', 'Mobile & Computer Shop'), ('GENERAL', 'General Store'), ('OTHER', 'Other Configurable Business')], default='RETAIL', max_length=50)),
                ('gst_enabled', models.BooleanField(default=True)),
                ('default_tax_mode', models.CharField(choices=[('exclusive', 'Tax Exclusive (Added at checkout)'), ('inclusive', 'Tax Inclusive (Included in product price)')], default='exclusive', max_length=20)),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5)),
                ('invoice_prefix', models.CharField(default='INV', max_length=20)),
                ('invoice_format', models.CharField(choices=[('a4', 'A4 Standard'), ('thermal_80mm', 'Thermal 80mm POS'), ('thermal_58mm', 'Thermal 58mm Compact')], default='a4', max_length=20)),
                ('allow_negative_stock', models.BooleanField(default=False)),
                ('low_stock_threshold', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=10)),
                ('credit_sales_enabled', models.BooleanField(default=True)),
                ('default_credit_limit', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), max_digits=12)),
                ('max_discount_cashier', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('max_discount_manager', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5)),
                ('custom_product_fields', models.JSONField(blank=True, default=list)),
                ('terms_and_conditions', models.TextField(blank=True, default='Goods once sold will be accepted for return/exchange within 7 days with original receipt.')),
                ('invoice_footer', models.TextField(blank=True, default='Thank you for your business! Visit again.')),
                ('auto_print', models.BooleanField(default=False)),
                ('auto_send_whatsapp', models.BooleanField(default=False)),
                ('require_customer', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Business Configuration',
                'verbose_name_plural': 'Business Configurations',
            },
        ),
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('cash_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('cash_refunds', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('cash_deposits', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('cash_withdrawals', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('expected_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('actual_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('difference', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_registers', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_registers', to='stores.store')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='HeldCart',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(default='Held Cart', max_length=150)),
                ('cart_data', models.JSONField(default=list)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('is_held', models.BooleanField(default=True)),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_carts', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_carts', to='customers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='held_carts', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
