# Generated by Django 5.1 on 2026-10-08 14:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_businessconfig_cashregister_heldcart'),
        ('organizations', '0001_initial'),
        ('stores', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSequence',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prefix', models.CharField(default='INV', max_length=20)),
                ('period_key', models.CharField(db_index=True, default='global', max_length=30)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_sequences', to='stores.store')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'prefix', 'period_key'], name='billing_inv_organiz_eede4c_idx')],
                'unique_together': {('organization', 'store', 'prefix', 'period_key')},
            },
        ),
    ]
