# Generated by Django 5.2.17 on 2026-08-12 10:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTimeline',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('created', 'Customer Created'), ('purchase', 'Purchase'), ('bill_sent', 'Bill Sent'), ('loyalty_earned', 'Loyalty Earned'), ('coupon_received', 'Coupon Received'), ('campaign_received', 'Campaign Received'), ('coupon_redeemed', 'Coupon Redeemed'), ('feedback', 'Feedback'), ('referral', 'Referral'), ('repeat_purchase', 'Repeat Purchase')], db_index=True, max_length=50)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name_plural': 'Customer timelines',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_id', models.CharField(db_index=True, max_length=50)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('anniversary_date', models.DateField(blank=True, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(choices=[('pos', 'POS Import'), ('api', 'API Import'), ('manual', 'Manual Entry'), ('web', 'Web Portal')], default='pos', max_length=50)),
                ('total_purchases', models.PositiveIntegerField(default=0)),
                ('total_spend', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_purchase_at', models.DateTimeField(blank=True, null=True)),
                ('segment', models.CharField(blank=True, db_index=True, max_length=50)),
                ('marketing_consent', models.BooleanField(default=True)),
                ('whatsapp_opt_in', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
