# Generated by Django 5.2.17 on 2026-08-12 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('organizations', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='preferred_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_customers', to='stores.store'),
        ),
        migrations.AddField(
            model_name='customertimeline',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='customertimeline',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['organization', 'segment'], name='customers_c_organiz_9ff770_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['organization', 'last_purchase_at'], name='customers_c_organiz_00096d_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['organization', 'total_spend'], name='customers_c_organiz_4fd7e5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('organization', 'phone')},
        ),
    ]
