# Generated by Django 5.1 on 2026-09-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
