# Generated by Django 5.1 on 2026-10-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_portal_token'),
        ('organizations', '0001_initial'),
        ('stores', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_walk_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='outstanding_credit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='customertimeline',
            name='event_type',
            field=models.CharField(choices=[('created', 'Customer Created'), ('purchase', 'Purchase'), ('bill_sent', 'Bill Sent'), ('loyalty_earned', 'Loyalty Earned'), ('coupon_received', 'Coupon Received'), ('campaign_received', 'Campaign Received'), ('coupon_redeemed', 'Coupon Redeemed'), ('feedback', 'Feedback'), ('referral', 'Referral'), ('repeat_purchase', 'Repeat Purchase'), ('credit_sale', 'Credit Sale'), ('credit_payment', 'Credit Payment'), ('sale_return', 'Sale Return')], db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['organization', 'outstanding_credit'], name='customers_c_organiz_f8991c_idx'),
        ),
    ]
