# Generated by Django 5.1 on 2026-10-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='custom_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('gst', 'GST Tax Invoice'), ('non_gst', 'Standard Bill / Non-GST'), ('thermal', 'Thermal Receipt'), ('credit_memo', 'Credit Note / Return')], default='gst', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='qr_code_data',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='template_format',
            field=models.CharField(choices=[('a4', 'A4 Standard'), ('thermal_80mm', '80mm Thermal'), ('thermal_58mm', '58mm Thermal')], default='a4', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='terms_and_conditions',
            field=models.TextField(blank=True),
        ),
    ]
