# Generated by Django 5.1 on 2026-10-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_quotation_quotationitem_and_more'),
        ('organizations', '0001_initial'),
        ('transactions', '0003_customercreditpayment_salesreturn_salesreturnitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('organization', 'invoice_number'), name='unique_org_invoice_number'),
        ),
    ]
