# Generated by Django 5.2.17 on 2026-08-12 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupons', '0002_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponredemption',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.transaction'),
        ),
        migrations.AlterUniqueTogether(
            name='coupon',
            unique_together={('organization', 'code')},
        ),
    ]
