# Generated by Django 5.1 on 2026-09-29 14:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='start_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
