# Generated by Django 5.1 on 2026-10-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_inventorymovement_purchaseorder_purchaseorderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='reference_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
