# Generated by Django 5.1 on 2026-10-07 14:41

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('products', '0003_inventorymovement_reference_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('gstin', models.CharField(blank=True, max_length=50)),
                ('pan', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='products.supplier'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['organization', 'name'], name='products_su_organiz_052df2_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['organization', 'is_active'], name='products_su_organiz_6e8c8a_idx'),
        ),
    ]
